
                                        MLab-Talk 介绍

                    1.MLab-Talk是基于融云开发的一款即时通讯app，若有任何疑问，可以访问融云首页。
                    2.MLab-Talk是专为南京工业大学矩阵实验室成员提供的交流工具。
                    3.矩阵实验室成员可根据自己的需要更改MLab-Talk的功能及UI界面。
                    4.未经所有成员允许，不可将此app给其他人使用，后期若要推广另议。

                                        最初版本研发成员为：汪小发

                                        MLab-Talk 工程简介

                    1.Lib目录下中放的是融云的环境配置文件
                    2.Framework目录下放的是融云需要的框架
                    3.Resource目录下放的是融云的是bundle资源包
                    4.Common目录下放的是成员的用户key，以及一些宏
                    5.MLab-Talk目录下放的是主要编写的代码文件
群组信息
groupId ：mlab
groupName：矩阵成员聊天室

成员的userId和tokenKey
汪小发 userId：mlabId_1
tokenKey：65rLhPM0qDE5jG8RUDrXE6Wd2JxAhydhUgOm5mmDQjERbjidWK1kvS93m0tnvo0BSzFUYKDa3Ux1gUBHAY1LfuFkhPtQyOB8

刘凯阳 userId：mlabId_2
tokenKey：N6ZEaug5UkFrKhulX56P1Bo6lCHML2t6tdfUnfdoD1zocua9MsU1Z4wFqVPvdqQq+Et23isHYrP0JJWh3skl50FNQbYWHpn4

吴友聪 userId：mlabId_3
tokenKey：9Fcl+MwazCvcNh0anUlvY6Wd2JxAhydhUgOm5mmDQjERbjidWK1kvUjcoE+bvfoVlhgACF5ooEgEMoGvRLmIsuFkhPtQyOB8

毕  澍 userId：mlabId_4
tokenKey：6m3fNM58fxv9CorHIajMQ6Wd2JxAhydhUgOm5mmDQjERbjidWK1kvd8uNV+J2DlqSzFUYKDa3UzX1CX+JMuwUuFkhPtQyOB8

王娅楠 userId：mlabId_5
tokenKey：pq4mwIdi0vxyJBD6+5HLL2sgWpBAtb0NQIDU75Ci1ZqMpNaJm8W9JgQyWsRxZbC1Cv45EX4yYk9MBUqqcB0Ivw==

